[package]
name = "ez-hash-cracker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha1 = "0.10"
sha2 = "0.10"
md5 = "0.7"
hex = "0.4"
